### ISSUE TITLE
US18: Refactor Styles

### ISSUE THREAD

**Issue by MariaRiosNavarro** [MariaRiosNavarro/mobileSimulation-propOS#34]
## Value Proposition

**As a** user
**I want to** have a beautiful app
**so that/in order to** enhance the visual appeal and aesthetics
​

## Description

Enhance the visual appeal and aesthetics, and create a similar end product to other well-designed applications.
​
## Acceptance Criteria

- [ ] Some Style changes are displayed

      
## Tasks

- [ ] Refactor Styles

**Comment by Danielschuetzle** [comment]
LGTM
